"""add todo edit history

Revision ID: 685109847a27
Revises: 881c1dc3854d
Create Date: 2026-03-10 17:16:30.671923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '685109847a27'
down_revision: Union[str, None] = '881c1dc3854d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('todos', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'todos', 'users', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'updated_by')
    op.drop_column('todos', 'updated_at')
    # ### end Alembic commands ###
